# Copyright(C) Facebook, Inc. and its affiliates.
import importlib.util
import sys
from os import chdir
from pathlib import Path

from fabric import task


_REPO_ROOT = Path(__file__).resolve().parent
_BENCHMARK_DIR = _REPO_ROOT / 'benchmark'


def _load_benchmark_fabfile():
    sys.path.insert(0, str(_BENCHMARK_DIR))
    previous = Path.cwd()
    chdir(_BENCHMARK_DIR)
    try:
        spec = importlib.util.spec_from_file_location(
            '_sfsailfish_benchmark_fabfile',
            _BENCHMARK_DIR / 'fabfile.py'
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    finally:
        chdir(previous)


_BENCHMARK_FABFILE = _load_benchmark_fabfile()


def _run_benchmark_task(task_obj, *args, **kwargs):
    previous = Path.cwd()
    chdir(_BENCHMARK_DIR)
    try:
        return task_obj.body(*args, **kwargs)
    finally:
        chdir(previous)


@task
def local(ctx, debug=False, consensus_only=True, header_size=512):
    """Run benchmarks on localhost."""
    return _run_benchmark_task(
        _BENCHMARK_FABFILE.local,
        ctx,
        debug=debug,
        consensus_only=consensus_only,
        header_size=header_size
    )


@task
def create(ctx, nodes=2):
    """Create a testbed."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.create, ctx, nodes=nodes)


@task
def destroy(ctx):
    """Destroy the testbed."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.destroy, ctx)


@task
def start(ctx):
    """Start at most `max` machines per data center."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.start, ctx)


@task
def stop(ctx):
    """Stop all machines."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.stop, ctx)


@task
def info(ctx):
    """Display connect information about all the available machines."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.info, ctx)


@task
def install(ctx):
    """Install the codebase on all machines."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.install, ctx)


@task
def remote(ctx, burst=50, debug=False, consensus_only=True, header_size=512_000):
    """Run benchmarks on GCP."""
    return _run_benchmark_task(
        _BENCHMARK_FABFILE.remote,
        ctx,
        burst=burst,
        debug=debug,
        consensus_only=consensus_only,
        header_size=header_size
    )


@task
def plot(ctx):
    """Plot performance using the logs generated by "fab remote"."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.plot, ctx)


@task
def kill(ctx):
    """Stop execution on all machines."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.kill, ctx)


@task
def logs(ctx):
    """Print a summary of the logs."""
    return _run_benchmark_task(_BENCHMARK_FABFILE.logs, ctx)
